language: java
services:
    - mysql
jdk:
    - oraclejdk7
    - openjdk6
before_script:
    - mysql -e "create database carpenter_sample"
    - mysql -D carpenter_sample < carpenter-core/src/test/resources/carpenter_sample.sql